channels:
    - conda-forge
    - eumetsat
dependencies:
  - python=3.9
  - epct=3.5.3
  - epct_webui=3.5.3
  - epct_restapi=3.5.3
  - epct_plugin_gis=3.4.2
  - msg-gdal-driver=0.4.0
  - epct_plugin_ncarrays=1.2.0
  - epct_plugin_netcdf_generator=3.2.1
  - epct_plugin_umarf=3.3.1
  - eumdac=3.0.0
